apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: podpreset-crd-system
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: podpreset-webook-configuration
  namespace: podpreset-crd-system
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6RENDQXJTZ0F3SUJBZ0lVTXhxc1BQTlgzUnhYZTR2ODRkekwydDZyalVnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZqRUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGxOdmRYUm9JRU5oY205c2FXNWhNUkV3RHdZRApWUVFIRXdoRGIyeDFiV0pwWVRFYU1CZ0dBMVVFQ2hNUmNHOWtjSEpsYzJWMExYTmxjblpwWTJVeEN6QUpCZ05WCkJBc1RBa05CTVJvd0dBWURWUVFERXhGd2IyUndjbVZ6WlhRdGMyVnlkbWxqWlRBZUZ3MHhPREE0TURFeE9ETXkKTURCYUZ3MHlNekEzTXpFeE9ETXlNREJhTUg0eEN6QUpCZ05WQkFZVEFsVlRNUmN3RlFZRFZRUUlFdzVUYjNWMAphQ0JEWVhKdmJHbHVZVEVSTUE4R0ExVUVCeE1JUTI5c2RXMWlhV0V4R2pBWUJnTlZCQW9URVhCdlpIQnlaWE5sCmRDMXpaWEoyYVdObE1Rc3dDUVlEVlFRTEV3SkRRVEVhTUJnR0ExVUVBeE1SY0c5a2NISmxjMlYwTFhObGNuWnAKWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPa3dVK2hnc1VPMktHWWpFVQpBbTlvSC9YcVRYZ2pJV2FhaVpzWHZVV3hnMDFONXA2SHcyZHJjdWhkeW9ma0p1d0d4QjBtYnB1LzJGdjhUaHhkCnI2ZGlUZGFkc1BPZGxpVE90eW03ZnhWU1VwRjJKRG5laWFwems0QU9wWjJqeXlMengwOEo3b2FkWE1FVVlDTG4KeVEvTy9UbzlJanRPNWR5VTJFbEp4N3JGUE1SaWhEK1FLczRLY2dlWUtqbzUyYnUrQ3lyUnJQYkhzNHlleHlPVApZZFRmUkJFSEdrRzVvTU03ZUtUaXFoZFBWRXhjUGh3SWE4UjRLdmZ2Q0FHUkJ0MFk1MmN3VnE1UkVXcWEvWnNxCjZXUlhzbEJyUjN5UlM3OHJITzZWdHpEWWw0MGtrbkV6MHpmVGxPNnh0aGRjS1ZFT1lCRTdQVVJ6NGZyd05FSzYKNVZFeEFnTUJBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCQmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwRwpBMVVkRGdRV0JCUm9tRDJwdXQ0c0tKeXFEZTJweHo3Wm1jZFRMakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCm8vUUMyZ3hDWmgxc1FDVVV0TnJUckpNZEtoQ1NmeUdvTUpZNWo4OWVBOUhTdWw5R20yZ1dDLzVZWmlldmxQMDMKQjBlZ2tRd1Z4MkNsVjFBOWRLTmFEYTBodmQzazdYenl1WTFkdlNQZWZoSWN2SGZVSklSczQzK0V4NmMxM0dkSgpiRDJZUC9NYUt2K3NQMll5T0ZLYUZvWDFjUVRqellSZDhaSk8rdEczazZENXRDLzVQRTFHaVFnbHZiSVgrM1E5CmFXQU9wc3F6NU1pU1dDMmpXSnUwUFByYkNyS2ZoSVJLZTN2VU5IV29iK3NyaXZ3VkZIQ0VFRkMzaW5YdWlYaG8KSitPSndpUElnL0tsOGpCQkUrUTVjS3JKc3N2VUFpbGxMWVNKeWdmMVlCcVFmeWlWWGJBY0xaRVlDN2pYdTZ2UQp2ZkJiU21DdUlMWnRvYUNzL2dESzN3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: podpreset-service
      namespace: podpreset-crd-system
      path: /mutating-pods
  failurePolicy: Fail
  name: podpresets.settings.svcat.k8s.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV3ekNDQTZ1Z0F3SUJBZ0lVQmhic3Y2dG9mTUh4UEJZaEpRcGV1QjREUnljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZqRUxNQWtHQTFVRUJoTUNWVk14RnpBVkJnTlZCQWdURGxOdmRYUm9JRU5oY205c2FXNWhNUkV3RHdZRApWUVFIRXdoRGIyeDFiV0pwWVRFYU1CZ0dBMVVFQ2hNUmNHOWtjSEpsYzJWMExYTmxjblpwWTJVeEN6QUpCZ05WCkJBc1RBa05CTVJvd0dBWURWUVFERXhGd2IyUndjbVZ6WlhRdGMyVnlkbWxqWlRBZUZ3MHhPREE0TURFeE9ETXkKTURCYUZ3MHhPVEE0TURFeE9ETXlNREJhTUlHWk1Rc3dDUVlEVlFRR0V3SlZVekVYTUJVR0ExVUVDQk1PVTI5MQpkR2dnUTJGeWIyeHBibUV4RVRBUEJnTlZCQWNUQ0VOdmJIVnRZbWxoTVJvd0dBWURWUVFLRXhGd2IyUndjbVZ6ClpYUXRjMlZ5ZG1salpURWFNQmdHQTFVRUN4TVJVRzlrVUhKbGMyVjBJRmRsWW1odmIyc3hKakFrQmdOVkJBTVQKSFhCdlpIQnlaWE5sZEMxelpYSjJhV05sTG1SbFptRjFiSFF1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXNCWU1CTFFHS2E1aWJNOHZ6enRQRGQxR0Z0Vy9vekxFcG42ckhTK1htTFZwCjV1d1I3Q0pZN25hZHRTMHJyS3hRTGFKN210QWxQa0tXSUJtR2tVTnNnT1ZodUJLbVI5dXVQWDd3akVlQWt4L0wKMlJjN3c5RW1GNkNUUU1SOEE4cTBGeGgwU3NuQjV4SXZLc0NUeDZoeE9jdDQrRHVSdWVnUmVnRjhhc1REb1d1ZwpOd1V6K2hrUlV5bzJyaVdJV1Q3ZmUwbDMrSDJXZEFoTTlwcEJnM1RUVmRvZnBSTFp4eGpaVE0xUGVMV1Zaa2JECjZsanJiVE1heHExWW1EOVlHdVRzY056OWVWSGR0YnZSdnJYY3NvdHRIUjVIdWZudWIwRU5IR2djT09NZzc5cXUKbTFDdzFITit5WEJvSms2ZHpKNzFTMjFEWjIxZDlqQVpETHVoNmN1Y093SURBUUFCbzRJQkd6Q0NBUmN3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WCkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRV0JCUURPcStHSUR4dHhQdjlrN2Y0YzRnZ0lFRktUVEFmQmdOVkhTTUUKR0RBV2dCUm9tRDJwdXQ0c0tKeXFEZTJweHo3Wm1jZFRMakNCbHdZRFZSMFJCSUdQTUlHTWdoRndiMlJ3Y21WegpaWFF0YzJWeWRtbGpaWUlkY0c5a2NISmxjMlYwTFhObGNuWnBZMlV1YTNWaVpTMXplWE4wWlcyQ0puQnZaSEJ5ClpYTmxkQzF6WlhKMmFXTmxMbkJ2WkhCeVpYTmxkQzFqY21RdGMzbHpkR1Z0Z2lwd2IyUndjbVZ6WlhRdGMyVnkKZG1salpTNXdiMlJ3Y21WelpYUXRZM0prTFhONWMzUmxiUzV6ZG1PSEJIOEFBQUV3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFNd1BzNUNkTFNUVTFBVUwya210d0pmTWx1alVuZ2lmOHVaY2tmeFVjSHI5QkpXeTJtSFo5Zlk3CmM1N2JWVEthQy90MWZTblZtNVpQWTNKekVnRXhHeXFUeG5MK3RIbVhpZVZPMU5VSExYVkEyYUxJTHRUenRQVE4KUFVIK2dJZ2ZHa1pnSkNUNWlTN21pSklaRW1Oc3MxTmREOGV0M1l5NSs3eG13NG5YODBjM2QvdTVuVlY5U0NDNApRcEdXYjJKN2NFckRGdURWak9kMGJ5RTlTWDQ0SThFRkpCb3g4K1pISklXOUQ1bVR3RkIraUczUVRLd1VDUDd4Cmhsc0pxZ2JjNHRHNlBRNGs5R1ROWTNjMzRZT0JzeURsd1JTbDVpanY4dFdJZ0pVNXMrZ3k2OWFXWHZTem1ma1cKL09hK0RuV3gwOStkaFFURUUvaGVYdGExLzZTaGlUYz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBc0JZTUJMUUdLYTVpYk04dnp6dFBEZDFHRnRXL296TEVwbjZySFMrWG1MVnA1dXdSCjdDSlk3bmFkdFMwcnJLeFFMYUo3bXRBbFBrS1dJQm1Ha1VOc2dPVmh1QkttUjl1dVBYN3dqRWVBa3gvTDJSYzcKdzlFbUY2Q1RRTVI4QThxMEZ4aDBTc25CNXhJdktzQ1R4Nmh4T2N0NCtEdVJ1ZWdSZWdGOGFzVERvV3VnTndVegoraGtSVXlvMnJpV0lXVDdmZTBsMytIMldkQWhNOXBwQmczVFRWZG9mcFJMWnh4alpUTTFQZUxXVlprYkQ2bGpyCmJUTWF4cTFZbUQ5WUd1VHNjTno5ZVZIZHRidlJ2clhjc290dEhSNUh1Zm51YjBFTkhHZ2NPT01nNzlxdW0xQ3cKMUhOK3lYQm9KazZkeko3MVMyMURaMjFkOWpBWkRMdWg2Y3VjT3dJREFRQUJBb0lCQVFDZzlaWkkybExqMlA4cApuWDZEZlNCM2VQUXZ2WFh1OVdKakcxakpWZzdLVGRLZmZ0Mm5MNEtCZ0xZS3ZsNjArZEpVMUxrT1BBUS9WRmlzCndRaU1Vc2lsVG9pejNZQllJVXkxOUFwcEFKZGNaVzFPWlhtQk52Y09FLzltN2ZTNjlwa0duNWoySUZWNkp0b3MKeDFxTzRMK1hhQktOUHM2bjFLWGRFK3lxSUhEL1pNQit0UXN1OTl0K29RaCsvSXduc3lZN3dVOSs4ZThTN0E3TgpBK2lBYkVXNXZuRXcxVjdCM041RjFSQVdtbWxMNHZZTWlwbVlnejdnTEZwS3NZVGFqSDE1UVBmWFdwN2NoVmw1CmNxT3c1M1o2aDdnTktlWFF5NE11UzMyNWRYRkxGNDZ0bDRHVDF6T3JGYXk1WXhFb1E4UHl6dGVIVjViWWsxYnAKRlk5V0d4a3BBb0dCQU1oSy9kZnIyM0VMYkdrUjNuMWVFWDVVNCtDVERsejhtdm80MmpHNkxjWkptZ05LTWlXdgpYWHN2TGVwUGM4L28wODBPSXdnb1RnbEdtZFRMR0tyUFQrSGVFU3lreXJ1NTFaYnhFdWtkTTlDRy9wS0ozV21HCjN5TWZGTzRDQXRHemEybnV0QTZScFdYS3kybTZCRXU0enhncXlKL1BveCtORDBFQ1YrNVhFS1VmQW9HQkFPRVAKZ3dpSjFCQzNpNmZUY1BSb21RdWFlRXRsQ1FRT0psTGNUUjNTbE5xb09xVS9xS1RaVUVVVmhPQWVNeVQzaGVkZgpKQzdWVHBxcG5zUStEVjVBZkwwdmF6MHRsdjF4UmR5WFJYQkJHUklIZjJmV2JaWjlSNVB0SW9RbWcxaGJkWmtWCmZIU0tIM25iTEx0QU9yUWt5a0sxc0JYekhTN3JWYXdxTndTa3A2bGxBb0dBVHBZdDl6UlJpNDlCNEEva3ppZkUKa1Y3WmNsb0F2cmRXVDJ0VElVTzloaG1HMWxlY1NYRC9Lc0FlTWRzdXc1ckV6NllHVk1NTHExUUtNNVhrZmRDTgp0VCtlV1hmbkc3VVVldjdudnBONHF3N3NmNjZjTXpWNkE1dkVhSVpkZU0zL0RUZGRhb0gyOVhPV1VFdHVPQSt4CklmaFhjMnpTd2lSa29jczdtUWFNUDEwQ2dZQTg1bnVvcGRNeXF0Z3BrN2V2QzFiT293QUdOdExYdkJSMnU1SksKalo4bUEvdktsNDFFL21FUU1LQ0NIT251Q09TOUZTdXZXSjBxa05lYmRzY2JTQXY1RFluUlJqTGpaZkZubmE5Mgpqc2IvNy9OejM3eEx5cDdCMHB0U2N6RjdpVlFyRm50VTljTktzQnBNbVRiSlpHTXU1Z2MrQ1VsT1Z2UVo0RnArCjhTZEZXUUtCZ1FDNVYzQi9RWnkvSGJwZi8zWFpCWGkvWVA1cHBrYUx2djNXN0VNZ1RBaHFuNHd1ME05QWQzREUKb2I1bnBFQlhwZ3JzeC9keU92b0QwcVZZTVpWWStjeHdTMGVQYm5UWERUenNqbTNHV0RqUEtVUHJrcEVTRFhHWApIMUx3ZElTVWxmR0p4ZmRmSmRRMll3NUY0THhERmp2bTRUNlFES3ByTnNDcEtoS0VxdmJuZEE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  name: podpreset-service-tls-d46dfbf5cm
  namespace: podpreset-crd-system
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: podpreset-service
  namespace: podpreset-crd-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: podpreset
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podpreset
  name: podpreset-webhook-deployment
  namespace: podpreset-crd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podpreset
  template:
    metadata:
      labels:
        app: podpreset
    spec:
      containers:
      - args:
        - -tls-cert-file=/keys/tls.crt
        - -tls-private-key-file=/keys/tls.key
        - -alsologtostderr
        - -v=6
        image: nikengp/admission-webhook:v0.4
        imagePullPolicy: IfNotPresent
        name: podpreset-webhook
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /keys
          name: tls-keys
      volumes:
      - name: tls-keys
        secret:
          secretName: podpreset-service-tls-d46dfbf5cm